server:
 port: 1975
 servlet:
  context-path: /tp12
spring:
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/XE
  username: system
  password: 123  
jpa:
 show_sql: true
 generate-ddl: true
 hibernate:
  ddl-auto: update
